# Generated by Django 3.1 on 2024-06-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='prefix',
            new_name='number',
        ),
    ]
